# Generated by Django 4.1.2 on 2022-10-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('hall', models.IntegerField()),
                ('chairs', models.CharField(max_length=10)),
                ('bar_stools', models.CharField(max_length=10)),
                ('TVs', models.CharField(max_length=10)),
                ('brown_tables', models.CharField(max_length=10)),
                ('white_tables', models.CharField(max_length=10)),
                ('beige_tables', models.CharField(max_length=10)),
                ('journal_tables', models.CharField(max_length=10)),
                ('bebra_trees', models.CharField(max_length=10)),
                ('sofas', models.CharField(max_length=10)),
                ('speakers', models.CharField(max_length=10)),
                ('mic', models.CharField(max_length=10)),
                ('mixer', models.CharField(max_length=10)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('tg', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=64)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
