# Generated by Django 4.1.2 on 2022-10-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_hardware_user_tvs_user_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='TVs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='bar_stools',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='bebra_trees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='beige_tables',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='brown_tables',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='chairs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='journal_tables',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='mic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='mixer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='sofas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='speakers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='white_tables',
            field=models.IntegerField(default=0),
        ),
    ]
