# Generated by Django 4.1.2 on 2022-10-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_tvs_alter_user_bar_stools_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('hall', models.IntegerField()),
                ('chairs', models.IntegerField(default=0)),
                ('bar_stools', models.IntegerField(default=0)),
                ('TVs', models.IntegerField(default=0)),
                ('brown_tables', models.IntegerField(default=0)),
                ('white_tables', models.IntegerField(default=0)),
                ('beige_tables', models.IntegerField(default=0)),
                ('journal_tables', models.IntegerField(default=0)),
                ('bebra_trees', models.IntegerField(default=0)),
                ('sofas', models.IntegerField(default=0)),
                ('speakers', models.IntegerField(default=0)),
                ('mic', models.IntegerField(default=0)),
                ('mixer', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='TVs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bar_stools',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bebra_trees',
        ),
        migrations.RemoveField(
            model_name='user',
            name='beige_tables',
        ),
        migrations.RemoveField(
            model_name='user',
            name='brown_tables',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chairs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='user',
            name='journal_tables',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mixer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sofas',
        ),
        migrations.RemoveField(
            model_name='user',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='white_tables',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
