# Generated by Django 4.1.2 on 2022-10-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_tvs_alter_user_bar_stools_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='TVs',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='bar_stools',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='bebra_trees',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='beige_tables',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='brown_tables',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='chairs',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='journal_tables',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='mic',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='mixer',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='sofas',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='speakers',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='white_tables',
            field=models.CharField(max_length=20),
        ),
    ]
