# Generated by Django 4.1.2 on 2022-10-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_tvs_alter_user_bar_stools_and_more'),
        ('user', '0005_alter_user_password'),
    ]

    operations = [
    ]
